### PR TITLE
Initial conversion of codebase to Ixcoin v0.9.4

### PR DESCRIPTION
**Pull request by GroundRod**
Numerous changes.  New Depends builder process, required client version & ixcoin-config.h changes as well as test procedure updates

### CODE REVIEW

**Comment by ahmedbodi** [comment]
Sweet. Looks good. I'm currently in the process of setting up my pool server so it'll be a few days before im able to test this. But when it's done i'll be able to test out the merged mining on a diff1 network so we can get quite a bit fixed then. 

Ahmed

**Comment by GroundRod** [comment]
Cleaning up the code a bit, transaction testing problems.  Which after these changes were made & compiled, the transaction test passes.  Reverted that one change you made Ahmed, that op return change in script.h to 80, broke the test, so it's temorary back to 40 until we can figure out what else needs to be fixed, before changing that define back to 80.

**Comment by GroundRod** [comment]
Sounds good Ahmed, workin off the todo thread with mmpool's lead, have various code changes in process, nothing that fixes a specific issue, except Checkpoints_test.cpp now passes.  Still you may want to grab the latest commit on what we have going so far, when testing that setup.  For example, just changed that MAX OP RETURN variable back to 40, and now pass the transaction IsStandard() test.  More work needs to be done there, before testing 80 again imo.

**Comment by GroundRod** [comment]
After more consideration, have set the BIP30 value back to what Ahmed had originally, this time with a correct date/time comment for the event, this should match what v8 nodes are doing now and be the best answer we have to security as the network migrates to v9 core technology.

Checkpoint test is now passing.

Decided to keep the checkpoint enable flag on, that along with other changes required to run specific test cases, can best be done locally, and not committed to our repo.  Anyone wishing to clone or pull the latest source, should be building a complete package, with all security measures intact, is the policy I'll try to adhere to.

**Comment by ahmedbodi** [comment]
Nice, although we do need to fix the tests and have them in the public repo. They're still set to the BTC/DVC defaults afaik

**Comment by GroundRod** [comment]
This shows you the tests I have compiling and linking into an execuable: 
IXCoin/src/Makefile.test.include
On linux, this then creates an executable as:
IXCoin/src/test/test_ixcoin

atm this runs 111 tests, all pass but two.  key_tests.cpp & miner_tests.cpp
I've spent hours on both, have not resolved the issues with either, for key tests I've generated correct compressed and uncompressed keys as new Ixc data, pretty sure that the test vectors are right on that, but the test still fails.
test/key_tests.cpp(58): error in "key_test1": check addr1.Get() == CTxDestination(pubkey1.GetID()) failed
test/key_tests.cpp(59): error in "key_test1": check addr2.Get() == CTxDestination(pubkey2.GetID()) failed
t
followed by more errors because of the above two.

On the mining_tests, it is still the same problem, as I mentioned before.  high-hash failure:
test/miner_tests.cpp(82): error in "CreateNewBlock_validity": check ProcessBlock(state, __null, pblock) failed

Hope that helps.

The QT and qa/rpc_tests have yet to be worked on, did add a comment to readme.md files in several folders, about how these were not yet tests that had been made fully functional.

**Comment by GroundRod** [comment]
Wanted to add this reply, to my comment on the Todo thread at BCT to our conversation, seemed relevent to my goal here of keeping our main repo as clean as possible of test code, and anyone can clone at anytime and have it build the client as we intend it to act for a working release...

Quote from: GroundRod on January 27, 2015, 09:38:12 AM
@mmpool - Now that I'm starting to understand the changes you've been making to allow the mining test to proceed, will not be putting those into our main development branch, but only on a local build to conduct the test. 

mmpool Re: Ixcoin TODO, January 27, 2015, 09:56:47 AM
This is the right thing to do, thanks. The changes are solely to allow testing on a new chain. I'll run another test in a day or two and post back with the results.

**Comment by GroundRod** [comment]
Dam was surprised by that missing Makefile in depends, so many files to cross check.  Thanks cinnamon, will fix the .gitignore here, so it shows up correctly and push that as well, we need that to be a part of the source, for sure.  

Unfortuately, I think that is one of a very few files, that if changed, causes all toolchains to be rebuilt.  So will get this done today.  

So watch out for it coming from me to correct that problem, if you don't want to rebuild the toolchain just then, don't run make in depends, until you have time to test it.

**Comment by GroundRod** [comment]
@cinnamoncoin - wow your making huge amounts of progress, really happy to hear!

@ahmedbodi - Cool, attempting the merge now...thanks

**Comment by GroundRod** [comment]
No, don't seem to have write access to do that merge yet...

**Comment by cinnamoncoin** [comment]
going to try to stay here / left you notes GR /on what other items were missing / after i built it all got linux ok but not win & did not try mac since I told you about my mac book pro. Next week or after will worry about mac. Now when i started compiling on linux (mint) got not very far after ./autogen.sh 
the failures are after where it checks g++ & gcc so going to have a go tonight to check into why. I really like the concept here building like this ... 
Should we be eventually looking to gitan though ... 

Once I get this to compile I can quickly run checks on everything. Thx :-)

**Comment by cinnamoncoin** [comment]
unrelated but fyi , Vlad added both of you to the ixcoin.org site as developers I noticed.

**Comment by GroundRod** [comment]
Know it's hard, when things have to be tried,  uninstalled etc, but if you could get a list of apt-get things that Mint did not have, that you needed, for the build to work, I sure would like that list.
Sounds like your real close.  The config.log being produced, may have clues near the end, not the easiest file to follow, but have solved many problems by careful study of it.

Someone sure could update the gitan build files, I won't be making it a priority, as I see it will be used less, once our new process in place and the builds are finally working properly with or without the depends toolchain.  Getting that for linux, mingw32 on windows and darwin on a mac are priority enough for right now.

Glad you like the new build process though.  Me too :)

Just got some more small edits to correct 'make deploy' so it works on building on a Mac, will push those up soon.

Added another small commit here, to fix .gitignore so that it specifically would allow the paticular Makefiles that we use which are now long term static, any other Makefiles are built during configure, and not needed with the source files.

Super on the ixcoin.org update for us.

**Comment by GroundRod** [comment]
Finally found the invite Ahmed had sent me way back on the 17th, and just now joined the team!  So should be able to merge pull requests.  Sorry about the delay in getting this added to the main repo, think that was the problem....

**Pull request merged**
